# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 里弄二巷
email: eeplover@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Enjoy yourself!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://eplover.github.io" # the base hostname & protocol for your site
twitter_username: eplover
github_username:  eplover

# Build settings
markdown: kramdown
